sudo: required
services:
  - docker

before_install:
  - docker build -t sachinsingh/webspace -f Dockerfile.dev .

script:
  - docker run -e CI=true sachinsingh/webspace npm test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "webspace-sachin"
  env: "webspace-sachin-env"
  bucket_name: "elasticbeanstalk-us-east-1-180294210078"
  bucket_path: "workspace-sachin"
  on: 
    branch: master
  access_key_id: $"AWS_ACCESS_KEY_ID"
  secret_access_key: $"AWS_SECRET_ACCESS_KEY"
    